/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.fyr_gui;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.awt.Toolkit;
import java.io.IOException;


public class SearchDataWindow extends javax.swing.JFrame {
    
    private int countId;
    private String dateTime;
    private String fileName;
    private int grade;
    private int modelType;
    private String imageBase64;

    /**
     * Creates new form GridView
     */
    public SearchDataWindow() {
        super( "Breast Cancer Grade Classification" );
        initComponents();
    }

    public SearchDataWindow(int countId, String dateTime, String fileName, int grade, int modelType,  String imageBase64) {
        super( "Breast Cancer Grade Classification" );
        initComponents();
        this.countId = countId;
        this.dateTime = dateTime;
        this.fileName = fileName;
        this.grade = grade;
        this.modelType=modelType;
        this.imageBase64 = imageBase64;
        sgwlblcid.setText(String.valueOf(countId));
        sgwlblfn.setText(fileName);
        sgwlbldt.setText(dateTime);
        sgwlblmt.setText(String.valueOf(modelType));
        sgwlblgc.setText(String.valueOf(grade));
        setImageIcon();
        sgwPnlData.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gvwbtnHome = new javax.swing.JButton();
        gvwbtnApp = new javax.swing.JButton();
        gvwbtnSearch = new javax.swing.JButton();
        sgwPnlData = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        sgwlblfn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sgwlbldt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sgwlblgc = new javax.swing.JLabel();
        sdwbtnPrint = new javax.swing.JButton();
        sdwbtnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sgwlblImage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sgwlblmt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sgwlblcid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().
            getImage("./images/logo.jpg"));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("View Data");

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setForeground(new java.awt.Color(102, 204, 255));

        gvwbtnHome.setBackground(new java.awt.Color(102, 204, 255));
        gvwbtnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gvwbtnHome.setForeground(new java.awt.Color(102, 102, 102));
        gvwbtnHome.setText("Home");
        gvwbtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvwbtnHomeActionPerformed(evt);
            }
        });

        gvwbtnApp.setBackground(new java.awt.Color(102, 204, 255));
        gvwbtnApp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gvwbtnApp.setForeground(new java.awt.Color(102, 102, 102));
        gvwbtnApp.setText("Application");
        gvwbtnApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvwbtnAppActionPerformed(evt);
            }
        });

        gvwbtnSearch.setBackground(new java.awt.Color(102, 204, 255));
        gvwbtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gvwbtnSearch.setForeground(new java.awt.Color(102, 102, 102));
        gvwbtnSearch.setText("Search");
        gvwbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvwbtnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gvwbtnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gvwbtnApp, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
            .addComponent(gvwbtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(gvwbtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gvwbtnApp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gvwbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        sgwPnlData.setBackground(new java.awt.Color(204, 255, 255));
        sgwPnlData.setForeground(new java.awt.Color(204, 255, 255));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("File name:");

        sgwlblfn.setBackground(new java.awt.Color(204, 255, 255));
        sgwlblfn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sgwlblfn.setForeground(new java.awt.Color(102, 102, 102));
        sgwlblfn.setText("test");

        jLabel5.setBackground(new java.awt.Color(204, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Date time: ");

        sgwlbldt.setBackground(new java.awt.Color(204, 255, 255));
        sgwlbldt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sgwlbldt.setForeground(new java.awt.Color(102, 102, 102));
        sgwlbldt.setText("test");

        jLabel7.setBackground(new java.awt.Color(204, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Grade Classification");

        sgwlblgc.setBackground(new java.awt.Color(204, 255, 255));
        sgwlblgc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sgwlblgc.setForeground(new java.awt.Color(102, 102, 102));
        sgwlblgc.setText("test");

        sdwbtnPrint.setBackground(new java.awt.Color(102, 204, 255));
        sdwbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sdwbtnPrint.setForeground(new java.awt.Color(102, 102, 102));
        sdwbtnPrint.setText("Export to PDF");
        sdwbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdwbtnPrintActionPerformed(evt);
            }
        });

        sdwbtnDelete.setBackground(new java.awt.Color(102, 204, 255));
        sdwbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sdwbtnDelete.setForeground(new java.awt.Color(102, 102, 102));
        sdwbtnDelete.setText("Delete");
        sdwbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdwbtnDeleteActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Image:");

        sgwlblImage.setBackground(new java.awt.Color(204, 255, 255));
        sgwlblImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sgwlblImage.setForeground(new java.awt.Color(102, 102, 102));
        sgwlblImage.setText("image");

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Model selection:");

        sgwlblmt.setBackground(new java.awt.Color(204, 255, 255));
        sgwlblmt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sgwlblmt.setForeground(new java.awt.Color(102, 102, 102));
        sgwlblmt.setText("test");

        jLabel6.setBackground(new java.awt.Color(204, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Record ID:");

        sgwlblcid.setBackground(new java.awt.Color(204, 255, 255));
        sgwlblcid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sgwlblcid.setForeground(new java.awt.Color(102, 102, 102));
        sgwlblcid.setText("test");

        javax.swing.GroupLayout sgwPnlDataLayout = new javax.swing.GroupLayout(sgwPnlData);
        sgwPnlData.setLayout(sgwPnlDataLayout);
        sgwPnlDataLayout.setHorizontalGroup(
            sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgwPnlDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sgwPnlDataLayout.createSequentialGroup()
                        .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sgwPnlDataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sgwlblmt, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(sgwPnlDataLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(sgwlblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(sgwPnlDataLayout.createSequentialGroup()
                        .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sdwbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sgwPnlDataLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sdwbtnPrint)
                                .addGap(192, 192, 192))
                            .addGroup(sgwPnlDataLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sgwlblgc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(sgwPnlDataLayout.createSequentialGroup()
                                        .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sgwlblfn, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sgwlbldt, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sgwlblcid, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        sgwPnlDataLayout.setVerticalGroup(
            sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgwPnlDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgwlblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sgwlblmt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sgwlblcid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sgwPnlDataLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sgwPnlDataLayout.createSequentialGroup()
                        .addComponent(sgwlblfn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sgwlbldt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgwlblgc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sgwPnlDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdwbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdwbtnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 514, Short.MAX_VALUE))
                    .addComponent(sgwPnlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sgwPnlData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setImageIcon() {
        try {
            byte[] imageBytes = javax.xml.bind.DatatypeConverter.parseBase64Binary(imageBase64);
            ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes);
            BufferedImage bImage = ImageIO.read(bis);
            Image newImg = new ImageIcon(bImage).getImage().getScaledInstance(sgwlblImage.getWidth(), sgwlblImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(newImg);
            sgwlblImage.setIcon(image);
        } catch (IOException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "An error occured while retrieving data!", "Error", JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(SearchDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void gvwbtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvwbtnHomeActionPerformed
        new HomeWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gvwbtnHomeActionPerformed

    private void gvwbtnAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvwbtnAppActionPerformed
        new ApplicationWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gvwbtnAppActionPerformed

    private void gvwbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvwbtnSearchActionPerformed
        new SearchWindow().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gvwbtnSearchActionPerformed

    private void sdwbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdwbtnPrintActionPerformed
        try {
            String st = "./reports/"+"report_" + dateTime.replace("-", "").replace(" ", "").replace(":", "") + ".pdf";
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream(st));
            doc.open();
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Breast Cancer Grade Classification Report",
                    new Font(Font.FontFamily.HELVETICA, 18.0f, Font.BOLD, BaseColor.BLACK)));
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Image :", new Font(Font.FontFamily.HELVETICA, 12.0f, Font.NORMAL, BaseColor.BLACK)));
            byte[] imageBytes = javax.xml.bind.DatatypeConverter.parseBase64Binary(imageBase64);
            com.itextpdf.text.Image img = com.itextpdf.text.Image.getInstance(imageBytes);
            doc.add(img);
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Record ID :", new Font(Font.FontFamily.HELVETICA, 12.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(new Paragraph(String.valueOf(countId), new Font(Font.FontFamily.HELVETICA, 10.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("File Name :", new Font(Font.FontFamily.HELVETICA, 12.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(new Paragraph(fileName, new Font(Font.FontFamily.HELVETICA, 10.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Selected Model :", new Font(Font.FontFamily.HELVETICA, 12.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(new Paragraph(String.valueOf(modelType), new Font(Font.FontFamily.HELVETICA, 10.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Executed date and time :", new Font(Font.FontFamily.HELVETICA, 12.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(new Paragraph(dateTime, new Font(Font.FontFamily.HELVETICA, 10.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(Chunk.NEWLINE);
            doc.add(new Paragraph("Grade :", new Font(Font.FontFamily.HELVETICA, 12.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.add(new Paragraph(String.valueOf(grade), new Font(Font.FontFamily.HELVETICA, 10.0f, Font.NORMAL, BaseColor.BLACK)));
            doc.close();
            File f = new File(st);
            Desktop.getDesktop().open(f);
        } catch (DocumentException | IOException ex) {
            System.out.println(ex);
            if("java.io.FileNotFoundException".equals(ex.getClass().getName())){
                JOptionPane.showMessageDialog(null, "The file is already opened!", "Warninig",
                    JOptionPane.WARNING_MESSAGE);     
            }
            else{
                JOptionPane.showMessageDialog(null, "An error Occured while exporting in to PDF format!", "Error",
                    JOptionPane.ERROR_MESSAGE);           
            }            
            java.util.logging.Logger.getLogger(SearchDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sdwbtnPrintActionPerformed

    private void sdwbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdwbtnDeleteActionPerformed
        try {
            BasicDBObject ob = new BasicDBObject();
            ob.put("date_time", dateTime);
            DBCursor cursor = Connector.con.find(ob);
            String st = null;
            while (cursor.hasNext()) {
                st = cursor.next().toString();
            }
            if (st == null) {
                JOptionPane.showMessageDialog(null, "No such record is found to remove!", "Error",
                        JOptionPane.ERROR_MESSAGE);
            } else {
                Connector.con.remove(ob);
                this.setVisible(false);
                new SecondWindow().setVisible(true);               
                JOptionPane.showMessageDialog(null, "Successfully removed the record!");               
            }
        } catch (HeadlessException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "An error occured while deleting!", "Error", JOptionPane.ERROR_MESSAGE);
            java.util.logging.Logger.getLogger(SearchDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sdwbtnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchDataWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SearchDataWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gvwbtnApp;
    private javax.swing.JButton gvwbtnHome;
    private javax.swing.JButton gvwbtnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sdwbtnDelete;
    private javax.swing.JButton sdwbtnPrint;
    private javax.swing.JPanel sgwPnlData;
    private javax.swing.JLabel sgwlblImage;
    private javax.swing.JLabel sgwlblcid;
    private javax.swing.JLabel sgwlbldt;
    private javax.swing.JLabel sgwlblfn;
    private javax.swing.JLabel sgwlblgc;
    private javax.swing.JLabel sgwlblmt;
    // End of variables declaration//GEN-END:variables
}
